/*
* generated by Xtext
*/
package org.xtext.dsl.dxl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DxlDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.dsl.dxl.ui.internal.DxlDslActivator.getInstance().getInjector("org.xtext.dsl.dxl.DxlDsl");
	}
	
}
