/**
 * generated by Xtext
 */
package org.xtext.dsl.dxl.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#labelProvider
 */
@SuppressWarnings("all")
public class DxlDslLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public DxlDslLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
}
