/*
 * generated by Xtext
 */
package org.xtext.dsl.dxl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DxlDslRuntimeModule extends org.xtext.dsl.dxl.AbstractDxlDslRuntimeModule {

}
