/*
* generated by Xtext
*/
package org.xtext.dsl.dxl;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DxlDslStandaloneSetup extends DxlDslStandaloneSetupGenerated{

	public static void doSetup() {
		new DxlDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

