/*
 * generated by Xtext
 */
package org.xtext.dsl.dxl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.dsl.dxl.ui.internal.DxlDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DxlDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DxlDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DxlDslActivator.getInstance().getInjector(DxlDslActivator.ORG_XTEXT_DSL_DXL_DXLDSL);
	}
	
}
