/*
 * generated by Xtext
 */
package org.xtext.dsl.dxl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DxlDslUiModule extends org.xtext.dsl.dxl.ui.AbstractDxlDslUiModule {
	public DxlDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
